/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Main.java
 *
 * Created on Dec 14, 2010, 7:50:40 PM
 */

package crawlhal;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.HashSet;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JToggleButton;

/**
 *
 * @author vigge
 */
public class Main extends javax.swing.JFrame {

    private static HashSet<URL> pending = new HashSet<URL>();
    private static LinkedList<String> output = new LinkedList<String>();
    private static HashSet<URL> crawled = new HashSet<URL>();

    public static boolean toggled = false;

    // Some stats for debugging purpose
    public static int linksAddedToPending = 0;
    public static int linksFound = 0;
    public static int linksTotal = 0;
    
    static {
       System.setProperty("swing.defaultlaf", "org.pushingpixels.substance.api.skin.SubstanceGeminiLookAndFeel");
    }
    /** Creates new form Main */
    public Main() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        urlToolBar = new javax.swing.JToolBar();
        urlLabel = new javax.swing.JLabel();
        urlField = new javax.swing.JTextField();
        crawlToggleButton = new javax.swing.JToggleButton();
        fillerLabel = new javax.swing.JLabel();
        outputScrollPane = new javax.swing.JScrollPane();
        outputTextArea = new javax.swing.JTextArea();
        statusBar = new org.jdesktop.swingx.JXStatusBar();
        statusLabel = new javax.swing.JLabel();
        pendingLabel = new javax.swing.JLabel();
        crawledLabel = new javax.swing.JLabel();
        crawlingLabel = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        newMenuItem = new javax.swing.JMenuItem();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        fileMenuSeparator1 = new javax.swing.JPopupMenu.Separator();
        closeMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        urlToolBar.setFloatable(false);
        urlToolBar.setRollover(true);

        urlLabel.setText("URL:");
        urlToolBar.add(urlLabel);
        urlToolBar.add(urlField);

        crawlToggleButton.setText("Crawl");
        crawlToggleButton.setFocusable(false);
        crawlToggleButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        crawlToggleButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        crawlToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crawlToggleButtonActionPerformed(evt);
            }
        });
        urlToolBar.add(crawlToggleButton);

        fillerLabel.setText(" ");
        urlToolBar.add(fillerLabel);

        outputScrollPane.setAlignmentX(0.0F);
        outputScrollPane.setAlignmentY(0.0F);
        outputScrollPane.setMaximumSize(new java.awt.Dimension(this.getSize()));
        outputScrollPane.setPreferredSize(new java.awt.Dimension(this.getSize()));

        outputTextArea.setColumns(20);
        outputTextArea.setEditable(false);
        outputTextArea.setRows(5);
        outputTextArea.setEnabled(false);
        outputTextArea.setMaximumSize(new java.awt.Dimension(this.getSize()));
        outputTextArea.setPreferredSize(new java.awt.Dimension(this.getSize()));
        outputScrollPane.setViewportView(outputTextArea);

        statusLabel.setText("Status");
        statusBar.add(statusLabel);

        pendingLabel.setText("Pending: 0");
        statusBar.add(pendingLabel);

        crawledLabel.setText("Crawled: 0");
        statusBar.add(crawledLabel);

        crawlingLabel.setText("crawling");
        statusBar.add(crawlingLabel);

        fileMenu.setText("File");

        newMenuItem.setText("New...");
        fileMenu.add(newMenuItem);

        openMenuItem.setText("Open...");
        fileMenu.add(openMenuItem);

        saveMenuItem.setText("Save...");
        fileMenu.add(saveMenuItem);
        fileMenu.add(fileMenuSeparator1);

        closeMenuItem.setText("Close");
        fileMenu.add(closeMenuItem);

        menuBar.add(fileMenu);

        jMenu2.setText("Edit");
        menuBar.add(jMenu2);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(urlToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(outputScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
            .addComponent(statusBar, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(urlToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(outputScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(statusBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-477)/2, (screenSize.height-330)/2, 477, 330);
    }// </editor-fold>//GEN-END:initComponents

    private void crawlToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crawlToggleButtonActionPerformed
        // Fetch the button from the event
        JToggleButton btn = (JToggleButton) evt.getSource();

        // Create a new crawler
        Crawler c = new Crawler();

        // If the button is selected we should run, if the button get's untoggled we should cancel
        if(btn.isSelected()){
            if(!urlField.getText().startsWith("http://") &&
               !urlField.getText().startsWith("https://")) {
                JOptionPane.showMessageDialog(rootPane, "Invalid URL\n Either there is no URL, or it doesn't start with http(s)://");
                btn.setSelected(false);
            } else {
                try {
                    // If the pending list is empty we should add our starting point
                    if(pending.isEmpty())
                        pending.add(new URL(urlField.getText()));
                } catch (MalformedURLException ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                }
                toggled = true;
                c.execute();
            }
        } else {
            c.cancel(true);
            updateStatus();
            toggled = false;
        }
    }//GEN-LAST:event_crawlToggleButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        JFrame.setDefaultLookAndFeelDecorated(true);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem closeMenuItem;
    private javax.swing.JToggleButton crawlToggleButton;
    private static javax.swing.JLabel crawledLabel;
    private static javax.swing.JLabel crawlingLabel;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JPopupMenu.Separator fileMenuSeparator1;
    private javax.swing.JLabel fillerLabel;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem newMenuItem;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JScrollPane outputScrollPane;
    private static javax.swing.JTextArea outputTextArea;
    private static javax.swing.JLabel pendingLabel;
    private javax.swing.JMenuItem saveMenuItem;
    private org.jdesktop.swingx.JXStatusBar statusBar;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JTextField urlField;
    private javax.swing.JLabel urlLabel;
    private javax.swing.JToolBar urlToolBar;
    // End of variables declaration//GEN-END:variables

    /**
     *
     * @return LinkedList<URL> a linked list with the URLs to crawl
     */
    public static HashSet<URL> getPending(){
        return pending;
    }

    /**
     * add an URL to the pending list
     * @param URL
     */
    public static void addToPending(URL URL){
        
        if(!crawled.contains(URL)) {
            pending.add(URL);
            linksAddedToPending++;
        } else {
            linksFound++;
        }
    }

    /**
     * Remove first object
     */
    public static void removeFromPending(URL url){
        pending.remove(url);
    }

    /**
     * Adds an URL to the crawled list
     * @param URL a URL to add
     */
    public static void addToCrawled(URL URL){
        crawled.add(URL);
    }

    /**
     * Update the output.
     * Truncates the output to 9 lines, currently
     * @param line a line to add
     */
    public static void appendToOutputArea(String line) {
        if(output.size() > 9){
            output.removeFirst();
        }
        output.addLast(line);

        String listOutput = "";
        for(int i = 0; i < output.size();i++){
            listOutput = listOutput +"\n"+ output.get(i);
        }
        outputTextArea.setText(listOutput);
    }

    /**
     * Update the status of the lists
     */
    public static void updateStatus(){
        pendingLabel.setText("Pending: "+pending.size());
        crawledLabel.setText("Crawled: "+crawled.size());
    }

    /**
     * Let the user know the current URL we are crawling
     * @param current
     */
    public static void setCurrentlyCrawling(String current){
        crawlingLabel.setText(current);
    }
}
